# frozen_string_literal: true

# #Twitter API v2
#
# Twitter API v2 available endpoints
#
# The version of the OpenAPI document: 2.62
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0
#

require "date"
require "time"

module Xbird
  class DmEvent
    attr_accessor :attachments, :created_at, :event_type, :text

    # Unique identifier of a DM conversation. This can either be a numeric string, or a pair of numeric strings separated by a '-' character in the case of one-on-one DM Conversations.
    attr_accessor :dm_conversation_id

    # Unique identifier of a DM Event.
    attr_accessor :id

    # A list of participants for a ParticipantsJoin or ParticipantsLeave event_type.
    attr_accessor :participant_ids

    # A list of Tweets this DM refers to.
    attr_accessor :referenced_tweets

    # Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    attr_accessor :sender_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'attachments': :attachments,
        'created_at': :created_at,
        'dm_conversation_id': :dm_conversation_id,
        'event_type': :event_type,
        'id': :id,
        'participant_ids': :participant_ids,
        'referenced_tweets': :referenced_tweets,
        'sender_id': :sender_id,
        'text': :text
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'attachments': :DmEventAttachments,
        'created_at': :Time,
        'dm_conversation_id': :String,
        'event_type': :String,
        'id': :String,
        'participant_ids': :'Array<String>',
        'referenced_tweets': :'Array<DmEventReferencedTweetsInner>',
        'sender_id': :String,
        'text': :String
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      raise ArgumentError, "The input argument (attributes) must be a hash in `Xbird::DmEvent` initialize method" unless attributes.is_a?(Hash)

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        unless self.class.attribute_map.key?(k.to_sym)
          raise ArgumentError,
                "`#{k}` is not a valid attribute in `Xbird::DmEvent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end

        h[k.to_sym] = v
      end

      self.attachments = attributes[:attachments] if attributes.key?(:attachments)

      self.created_at = attributes[:created_at] if attributes.key?(:created_at)

      self.dm_conversation_id = attributes[:dm_conversation_id] if attributes.key?(:dm_conversation_id)

      self.event_type = attributes[:event_type] if attributes.key?(:event_type)

      self.id = attributes[:id] if attributes.key?(:id)

      if attributes.key?(:participant_ids) && (value = attributes[:participant_ids]).is_a?(Array)
        self.participant_ids = value
      end

      if attributes.key?(:referenced_tweets) && (value = attributes[:referenced_tweets]).is_a?(Array)
        self.referenced_tweets = value
      end

      self.sender_id = attributes[:sender_id] if attributes.key?(:sender_id)

      return unless attributes.key?(:text)

      self.text = attributes[:text]
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = []
      pattern = Regexp.new(/^([0-9]{1,19}-[0-9]{1,19}|[0-9]{15,19})$/)
      invalid_properties.push("invalid value for \"dm_conversation_id\", must conform to the pattern #{pattern}.") if !@dm_conversation_id.nil? && @dm_conversation_id !~ pattern

      invalid_properties.push('invalid value for "event_type", event_type cannot be nil.') if @event_type.nil?

      invalid_properties.push('invalid value for "id", id cannot be nil.') if @id.nil?

      pattern = Regexp.new(/^[0-9]{1,19}$/)
      invalid_properties.push("invalid value for \"id\", must conform to the pattern #{pattern}.") if @id !~ pattern

      invalid_properties.push('invalid value for "participant_ids", number of items must be greater than or equal to 1.') if !@participant_ids.nil? && @participant_ids.empty?

      invalid_properties.push('invalid value for "referenced_tweets", number of items must be greater than or equal to 1.') if !@referenced_tweets.nil? && @referenced_tweets.empty?

      pattern = Regexp.new(/^[0-9]{1,19}$/)
      invalid_properties.push("invalid value for \"sender_id\", must conform to the pattern #{pattern}.") if !@sender_id.nil? && @sender_id !~ pattern

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@dm_conversation_id.nil? && @dm_conversation_id !~ Regexp.new(/^([0-9]{1,19}-[0-9]{1,19}|[0-9]{15,19})$/)
      return false if @event_type.nil?
      return false if @id.nil?
      return false if @id !~ Regexp.new(/^[0-9]{1,19}$/)
      return false if !@participant_ids.nil? && @participant_ids.empty?
      return false if !@referenced_tweets.nil? && @referenced_tweets.empty?
      return false if !@sender_id.nil? && @sender_id !~ Regexp.new(/^[0-9]{1,19}$/)

      true
    end

    # Custom attribute writer method with validation
    # @param [Object] dm_conversation_id Value to be assigned
    def dm_conversation_id=(dm_conversation_id)
      pattern = Regexp.new(/^([0-9]{1,19}-[0-9]{1,19}|[0-9]{15,19})$/)
      raise ArgumentError, "invalid value for \"dm_conversation_id\", must conform to the pattern #{pattern}." if !dm_conversation_id.nil? && dm_conversation_id !~ pattern

      @dm_conversation_id = dm_conversation_id
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      raise ArgumentError, "id cannot be nil" if id.nil?

      pattern = Regexp.new(/^[0-9]{1,19}$/)
      raise ArgumentError, "invalid value for \"id\", must conform to the pattern #{pattern}." if id !~ pattern

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] participant_ids Value to be assigned
    def participant_ids=(participant_ids)
      raise ArgumentError, 'invalid value for "participant_ids", number of items must be greater than or equal to 1.' if !participant_ids.nil? && participant_ids.empty?

      @participant_ids = participant_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] referenced_tweets Value to be assigned
    def referenced_tweets=(referenced_tweets)
      if !referenced_tweets.nil? && referenced_tweets.empty?
        raise ArgumentError,
              'invalid value for "referenced_tweets", number of items must be greater than or equal to 1.'
      end

      @referenced_tweets = referenced_tweets
    end

    # Custom attribute writer method with validation
    # @param [Object] sender_id Value to be assigned
    def sender_id=(sender_id)
      pattern = Regexp.new(/^[0-9]{1,19}$/)
      raise ArgumentError, "invalid value for \"sender_id\", must conform to the pattern #{pattern}." if !sender_id.nil? && sender_id !~ pattern

      @sender_id = sender_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        attachments == other.attachments &&
        created_at == other.created_at &&
        dm_conversation_id == other.dm_conversation_id &&
        event_type == other.event_type &&
        id == other.id &&
        participant_ids == other.participant_ids &&
        referenced_tweets == other.referenced_tweets &&
        sender_id == other.sender_id &&
        text == other.text
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attachments, created_at, dm_conversation_id, event_type, id, participant_ids, referenced_tweets, sender_id,
       text].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            send("#{key}=", attributes[self.class.attribute_map[key]].map do |v|
                              _deserialize(::Regexp.last_match(1), v)
                            end)
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Xbird.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
