inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'lib/xbird/**/*'

Lint/SuppressedException:
  Exclude:
    - 'lib/xbird/**/*'

Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'lib/xbird/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'lib/xbird/**/*'

Metrics:
  Enabled: false
