# frozen_string_literal: true

# #Twitter API v2
#
# Twitter API v2 available endpoints
#
# The version of the OpenAPI document: 2.62
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for Xbird::AddOrDeleteRulesRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Xbird::AddOrDeleteRulesRequest do
  describe ".openapi_one_of" do
    it "lists the items referenced in the oneOf array" do
      expect(described_class.openapi_one_of).to_not be_empty
    end
  end

  describe ".build" do
    it "returns the correct model" do
    end
  end
end
