# frozen_string_literal: true

# #Twitter API v2
#
# Twitter API v2 available endpoints
#
# The version of the OpenAPI document: 2.62
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for Xbird::ClientForbiddenProblemAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Xbird::ClientForbiddenProblemAllOf do
  let(:instance) { Xbird::ClientForbiddenProblemAllOf.new }

  describe "test an instance of ClientForbiddenProblemAllOf" do
    it "should create an instance of ClientForbiddenProblemAllOf" do
      expect(instance).to be_instance_of(Xbird::ClientForbiddenProblemAllOf)
    end
  end
  describe 'test attribute "reason"' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["official-client-forbidden", "client-not-enrolled"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reason = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "registration_url"' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
