# frozen_string_literal: true

# #Twitter API v2
#
# Twitter API v2 available endpoints
#
# The version of the OpenAPI document: 2.62
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.5.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for Xbird::InvalidRuleProblem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Xbird::InvalidRuleProblem do
  let(:instance) { Xbird::InvalidRuleProblem.new }

  describe "test an instance of InvalidRuleProblem" do
    it "should create an instance of InvalidRuleProblem" do
      expect(instance).to be_instance_of(Xbird::InvalidRuleProblem)
    end
  end
end
